#!/usr/bin/env bash
# DST dedicated server — Vultr VPS one-shot bootstrap.
#
# Usage (on a fresh root SSH session into an Ubuntu 22.04 / 24.04 Vultr VPS):
#
#   curl -fsSL https://raw.githubusercontent.com/moxxiq/dst-dedicated-container/master/bootstrap/vultr-bootstrap.sh -o bootstrap.sh
#   chmod +x bootstrap.sh
#   sudo ./bootstrap.sh
#
# The script prompts interactively for secrets (admin panel password, Klei
# cluster token, optional Cloudflare R2 keys). Nothing is baked into this
# file — it's safe to commit and safe to rerun.
#
# After it finishes you'll have:
#   - A `dst` Linux user owning ~/steamCMD
#   - The DST container running under rootless podman (restart=unless-stopped)
#   - The FastAPI admin panel on :8080 (HTTP Basic)
#   - Optionally the Beszel monitoring stack (:8090) if you opt in
#
# Re-running is idempotent: existing users/clones/containers are reused.

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/moxxiq/dst-dedicated-container.git}"
DST_USER="${DST_USER:-dst}"
DST_HOME="/home/${DST_USER}"
TARGET="${TARGET:-${DST_HOME}/steamCMD}"
CLUSTER_NAME_DEFAULT="qkation-cooperative"

say() { printf '\n\033[1;36m== %s ==\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*" >&2; }
die() { printf '\033[1;31mx %s\033[0m\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root (sudo ./bootstrap.sh)."

# ---- 1. Interactive prompts -------------------------------------------------
say "Interactive setup"
# Use /dev/tty so prompts work even when the script is piped.
exec 3</dev/tty 4>/dev/tty || die "No controlling TTY. SSH in interactively first."

read -r -u3 -p "Cluster name [${CLUSTER_NAME_DEFAULT}]: " CLUSTER_NAME
CLUSTER_NAME="${CLUSTER_NAME:-$CLUSTER_NAME_DEFAULT}"

read -r -u3 -p "Klei cluster token (paste from accounts.klei.com): " CLUSTER_TOKEN
[[ -n "$CLUSTER_TOKEN" ]] || warn "Empty cluster token — DST will not start until you set it."

read -r -u3 -p "Admin panel username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"

while :; do
  read -r -u3 -s -p "Admin panel password (required, min 8 chars): " ADMIN_PASSWORD; echo
  read -r -u3 -s -p "Repeat: " ADMIN_PASSWORD2; echo
  if [[ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD2" ]]; then warn "Mismatch, try again."; continue; fi
  if [[ ${#ADMIN_PASSWORD} -lt 8 ]]; then warn "Too short."; continue; fi
  break
done

say "Cloudflare R2 backup (optional — press Enter on all four to skip)"
read -r -u3 -p "R2 account ID:       " R2_ACCOUNT_ID
read -r -u3 -p "R2 bucket:           " R2_BUCKET
read -r -u3 -p "R2 access key ID:    " R2_ACCESS_KEY_ID
read -r -u3 -s -p "R2 secret key:       " R2_SECRET_ACCESS_KEY; echo

read -r -u3 -p "Also install Beszel monitoring (:8090)? [y/N]: " INSTALL_BESZEL
INSTALL_BESZEL="${INSTALL_BESZEL,,}"  # lowercase

# ---- 2. System packages -----------------------------------------------------
say "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends \
  podman git rsync ca-certificates uidmap slirp4netns fuse-overlayfs \
  dbus-user-session systemd-container

# ---- 3. User + rootless runtime --------------------------------------------
say "Creating ${DST_USER} user"
if ! id "$DST_USER" >/dev/null 2>&1; then
  useradd -m -s /bin/bash "$DST_USER"
fi
loginctl enable-linger "$DST_USER"

as_dst() { sudo -u "$DST_USER" -H XDG_RUNTIME_DIR="/run/user/$(id -u "$DST_USER")" "$@"; }

# ---- 4. Clone the repo ------------------------------------------------------
say "Fetching repo at ${TARGET}"
if [[ -d "$TARGET/.git" ]]; then
  as_dst git -C "$TARGET" pull --ff-only || warn "git pull failed; keeping existing checkout."
else
  sudo -u "$DST_USER" -H git clone "$REPO_URL" "$TARGET"
fi

# ---- 5. Write .env (DST + admin) -------------------------------------------
say "Writing ${TARGET}/.env"
umask 077
cat > "$TARGET/.env" <<EOF
# Generated by vultr-bootstrap.sh on $(date -Is)
CLUSTER_NAME=${CLUSTER_NAME}
CLUSTER_TOKEN=${CLUSTER_TOKEN}

R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
R2_BUCKET=${R2_BUCKET}
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}

AUTO_UPDATE=1

ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
chown "$DST_USER:$DST_USER" "$TARGET/.env"
chmod 0600 "$TARGET/.env"
umask 022

# ---- 6. Bind-mount ownership ------------------------------------------------
mkdir -p "$TARGET/saves" "$TARGET/mods" "$TARGET/parked"
chown -R "$DST_USER:$DST_USER" "$TARGET"
# Inside the DST container the app runs as UID 1000, which for rootless podman
# maps to the host's DST_USER (first subuid slot). The :U flag in compose/
# run-dst.sh handles the chown on mount, so no further tweaks needed here.

# ---- 7. Build & start DST ---------------------------------------------------
say "Building DST image"
as_dst bash -c "cd '$TARGET' && podman build --platform=linux/amd64 -t local/steamcmd:latest ."

say "Starting DST container"
as_dst bash -c "cd '$TARGET' && ./run-dst.sh start"

# ---- 8. Build & start admin panel ------------------------------------------
say "Building admin panel image"
as_dst bash -c "cd '$TARGET/admin' && podman build --platform=linux/amd64 -t local/dst-admin:latest ."

say "Starting admin panel"
as_dst bash -c "cd '$TARGET/admin' && podman compose up -d"

# ---- 9. Optional Beszel monitoring -----------------------------------------
if [[ "$INSTALL_BESZEL" == "y" || "$INSTALL_BESZEL" == "yes" ]]; then
  say "Starting Beszel monitoring"
  as_dst bash -c "cd '$TARGET/monitoring' && podman compose up -d"
fi

# ---- 10. Summary ------------------------------------------------------------
VPS_IP="$(hostname -I | awk '{print $1}')"
say "Bootstrap complete"
cat <<EOF

  DST container     : podman logs -f dst        (as ${DST_USER})
  Admin panel       : http://${VPS_IP}:8080     (user: ${ADMIN_USER})
$( [[ "$INSTALL_BESZEL" == "y" || "$INSTALL_BESZEL" == "yes" ]] && echo "  Beszel monitoring : http://${VPS_IP}:8090" )

  Next steps:
    1. Open Vultr Cloud Firewall and allow:
         UDP  10999       from anywhere   (DST game)
         UDP  8766        from anywhere   (Steam auth)
         UDP  27016       from anywhere   (Steam master)
         TCP  22          from your IP    (SSH)
         TCP  8080        from your IP    (admin panel)$( [[ "$INSTALL_BESZEL" == "y" || "$INSTALL_BESZEL" == "yes" ]] && echo "
         TCP  8090        from your IP    (Beszel UI)" )
    2. Open http://${VPS_IP}:8080 and either:
         - upload an existing cluster zip, or
         - use the template wizard to create a new world.
    3. DST is currently waiting for a cluster — it will pick up the files
       within 5 seconds of the admin panel writing them.

  To re-run this bootstrap on a new VPS, download the latest .env from
  the admin panel ("Download bootstrap.sh") — it bakes in all the secrets
  so the next paste needs zero extra typing.
EOF
